name: Try run e2e
on: push
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Download project
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.2

      - name: Install dependencies
        run: yarn install

      - name: Buld backstage
        run: yarn build:all

      - name: Run e2e
        run: yarn test:e2e
