name: Try run e2e
on: push
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Download project
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.2

      - name: Install dependencies
        run: |
          yarn install
          yarn add --cwd packages/backend sqlite3

      - name: Create SQLite database
        run: |
          echo "CREATE TABLE example (id INTEGER PRIMARY KEY, name TEXT);" > example.sql
          sqlite3 mydb.db < example.sql

      - name: Start backend
        run: |
          yarn build:backend
          yarn start-backend &
          sleep 20  # Wait for the backend to start
          nc -zv localhost 7007

      - name: Run e2e
        run: yarn test:e2e
        env:
          CI: true
