name: Try run e2e
on: push
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Download project
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install --frozen-lockfile | yarn tsc

      - name: Buld backstage
        run: yarn build:all

      - name: Start backend
        run: yarn start-backend

      - name: Run e2e
        run: yarn test:e2e
