name: Try run e2e
on: push
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Download code
        uses: actions/checkout@v3
      - name: Build backend docker image
        run: |
          yarn
          yarn build:backend
          yarn build-image
      - name: Buld frontend
        run: yarn install --frozen-lockfile
      - name: Run e2e
        run: yarn test:e2e 
