name: Try run e2e
on: push
jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: vm
          POSTGRES_USER: vm
          POSTGRES_PASSWORD: secret
    steps:
      - name: Download project
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.18.2

      - name: Install dependencies
        run: | 
          yarn install
          yarn add --cwd packages/backend pg

      - name: Start PostgreSQL
        run: |
          # Wait for PostgreSQL to be ready before starting the backend
          sleep 10

      - name: Check PostgreSQL Connection
        run: |
          PGPASSWORD=secret psql -h localhost -U vm -d vm -c "SELECT 1;"    

      - name: Start backend
        run: | 
          yarn build:backend
          yarn start-backend &
          sleep 30  # Wait for the backend to start
          nc -zv localhost 7007          

      - name: Buld backstage
        run: yarn build:all

      - name: Run e2e
        run: yarn test:e2e
        env:
          CI: true
